Fix odl-tsdr-restconf-collector SFT failure
 org.osgi.service.blueprint.container.ComponentDefinitionException: Error when instantiating bean .component-1 of class org.opendaylight.restconf.nb.bierman02.web.noauth.WebInitializer
02:49:35 	at org.apache.aries.blueprint.container.BeanRecipe.wrapAsCompDefEx(BeanRecipe.java:361)
...
Caused by: java.lang.IllegalStateException: Http context already used. Context params can be set/changed only before first usage
02:49:35 	at org.ops4j.pax.web.service.internal.HttpServiceStarted.setContextParam(HttpServiceStarted.java:707)

Removed the features-restconf and features-aaa dependencies from the pom.
These are feature repos and not intended to be installed as features.

Change-Id: Ia1a8a5066d6e301adbc8812d8d91d0e03ea38716
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>